### ISSUE TITLE
lazy create elements

### ISSUE THREAD

**Issue by CoderCat84** [helion3/inspire-tree#103] opened 2016-11-29 00:40 UTC
I load 1360 items at the root level in the tree and there is a second long hang in the app when the tree loads that is traced to createElement where it creates the elements for all of the nodes (there are not yet any children under tehse nodes).  Since most of them are not visible it would be great if the elements were not created until scrolled into view to prevent my application from hanging.

**Comment by viveleroi** [comment] 2016-11-29 01:11
Can you clarify how you're measuring the performance, and in which browser/OS?

I generated a fake json file with 1000 root nodes and in Chrome on Mac OS it's taking about 200ms to parse and render those nodes. That doesn't include the 240ms the xhr request takes. That averages out to another 80ms if I had 1400 nodes. < 300ms doesn't seem to match the results you're getting so anything you can clarify would be helpful.

None the less, rendering nodes on the fly is a good idea.

**Comment by CoderCat84** [comment] 2016-11-29 03:01
I'm using chrome and I'm using the timeline view in chrome to measure performance.  Operating system is windows 7.  The time I'm measuring all is within createElement within renderNodes on the line:

  dom.rootNode = (0, _virtualDom.create)(newOl)

which is calling createElement (which calls itself for the children of the node)

**Comment by benjymous** [comment] 2016-11-29 15:45
I can confirm I noticed similar slowdown with a large number (tens of thousands) of leaf nodes when dynamically loading a node's children.

My workaround is just to add more intermediate levels to try and minimise the number of children any particular node has.

Perhaps an option could be added to do this automatically, in a similar way to Chrome's js debugger displays large arrays - splitting them into 0-999, 1000-1999. 2000-2999, groups, etc

**Comment by viveleroi** [comment] 2016-11-29 16:41
That's not far off from what I've been toying with. So far I see two core requirements needed to offset loading/rendering costs with large node lists like these:

**Deferred rendering.** 

The issue as-filed refers to "lazy create elements" which I'll officially be calling "deferred rendering". The concept is the same though - deferred building of the actual DOM elements for nodes trigged by their visibility within a scrollable parent. This means we'll start by building an initial set of DOM elements, and build more as the user scrolls. 

I already have a rough implementation working. I want to generate a larger dataset to test with and I want to toy around with different overflow settings to make sure it works well.

**Deferred loading**

This hasn't been mentioned specifically but feels like an essential partner to deferred rendering. In my timings it was taking 240ms for the xhr to complete - loading a json file with 1000 nodes and no children - and that's a from a static file on a local nginx server. If that were real json data coming from a slower server-side language like apache/php that has to query a database, it could very well take a whole second on it's own.

Since deferred rendering takes care of rendering nodes that have already loaded, I should add a way to load nodes in batches. We already allow for dynamic children but this could allow users to break up same-level nodes into multiple requests.

I haven't started work on that so I'm not sure how I'll implement it, but I would imagine it'll be similar to how I decide which nodes to render - just with a larger buffer since loading takes longer.

**Comment by viveleroi** [comment] 2016-11-30 02:23
I've got a first round of deferred rendering done in this branch: https://github.com/helion3/inspire-tree/tree/deferred-rendering (note: only `src` files are update, if you're testing).

It works well but I've realized it's going to have to work for child nodes too and that's going to need additional work because they can complicate the scroll math.

I've started work on the deferred loading too but that's going to depend on this work, so it'll come later.

**Comment by viveleroi** [comment] 2016-12-03 00:35
Step one of likely three has been pushed to master. With this, the user can use a "Load More" link to render additional nodes. I wanted to get the logic right before I worried about trying to automatically load based on scroll position - which isn't easy when you're dealing with nested spaces. I have some decent work started on that phase but I'm not 100% sure there won't be any more snags.

So hopefully, automatically rendering on scroll is phase two. Phase 3 is implementing deferred loading, so that you don't have to front-load all the nodes.

**Comment by viveleroi** [comment] 2016-12-03 00:36
Unrelated, but good to know, is that I'm also doing work to move us to a better (smaller and faster) rendering engine. That will help a bit too.

**Comment by CoderCat84** [comment] 2016-12-05 16:34
Thanks for this work it looks like it will be awesome.

**Comment by SharpieX** [comment] 2016-12-07 09:54
i am working with 4000 rows and i can see lag also in rendering and loading as well I tried both treeOptions
`deferredLoading: true,
dom: {
		deferredRendering: true
},`

**Comment by SharpieX** [comment] 2016-12-07 10:46
In my Angular 1.5 app I am working with array of nested objects , root contains 8 node and those nodes holding approx 4000 childrens to remove lag in rendering i deferrdRendering , i can still see the lag ,
and pagination also not working all nodes are present and seems other treeOptions like checkbox are also not working me as well  
Am I missing something here ?
$scope.treeOptions = {
data: treeColumns,
dom: {
deferredRendering: true
},
pagination: {
limit:30
},
onRegisterApi: function (api) {
$scope.tree = api ;
}
}

**Comment by CoderCat84** [comment] 2017-01-18 13:33
Hi, 
Is there a plan to release this?  I see related commits but no release

Thanks!

**Comment by viveleroi** [comment] 2017-01-19 01:50
I was hoping to release this with a new rendering system I've completed but there are a few unresolved engine issues preventing me from doing that. I'll probably have to hold the rendering changes for a future release. Now that the holidays are over I need to re-evaluate and get a release out soon.

**Comment by viveleroi** [comment] 2017-02-16 23:29
This work went out with the 1.11 release, so I'll close the issue.

**Closed by viveleroi** 2017-02-16 23:29 UTC
